version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_dotnet_app
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: my_mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: voucherDb
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: voucher@123
    ports:
      - "3306:3306"
