version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: VoucherManagement\Dockerfile
    container_name: my_dotnet_app
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:latest
    container_name: my_mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: voucherDb
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: voucher@123
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
